apiVersion: v1
kind: Secret
metadata:
  name: tempconverter-secret
  namespace: tempconverter
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  DB_USER: tempuser
  DB_PASS: temppassword123
  DB_NAME: tempconverter